# Generated by Django 4.2.11 on 2024-03-22 15:07

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('username', models.CharField(blank=True, max_length=50, null=True)),
                ('cpf', models.CharField(max_length=14, unique=True)),
                ('TelCelular', models.CharField(max_length=16)),
                ('dtNascimento', models.DateField(null=True)),
                ('genero', models.CharField(choices=[('1', 'Masculino'), ('2', 'Feminino'), ('3', 'Outro')], max_length=1)),
                ('matricula', models.CharField(max_length=8, primary_key=True, serialize=False, unique=True)),
                ('turma_aluno', models.CharField(max_length=2)),
                ('contrato', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id_disciplina', models.AutoField(primary_key=True, serialize=False)),
                ('nome_disciplina', models.CharField(max_length=80)),
                ('duracao_disciplina', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Graduacao',
            fields=[
                ('id_curso', models.AutoField(primary_key=True, serialize=False)),
                ('nome_curso', models.CharField(max_length=100)),
                ('categoria_curso', models.CharField(choices=[('1', 'Bacharelado'), ('2', 'Licenciatura'), ('3', 'Tecnólogo')], max_length=1)),
                ('duracao_curso', models.CharField(max_length=50)),
                ('area_curso', models.CharField(choices=[('1', 'Ciências Exatas e da Terra'), ('2', 'Ciências Biológicas'), ('3', 'Engenharias'), ('4', 'Ciências da Saúde'), ('5', 'Ciências Agrárias'), ('6', 'Ciências Humanas'), ('7', 'Linguística, Letras e Artes'), ('8', 'Ciências Sociais Aplicadas')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id_turma', models.AutoField(primary_key=True, serialize=False)),
                ('nome_turma', models.CharField(max_length=50)),
                ('turno_turma', models.CharField(choices=[('1', 'Matutino'), ('2', 'Vespertino'), ('3', 'Noturno')], max_length=1)),
                ('semestre_turma', models.CharField(choices=[('1', '1° Semestre'), ('2', '2° Semestre'), ('3', '3° Semestre'), ('4', '4° Semestre'), ('5', '5° Semestre'), ('6', '6° Semestre'), ('7', '7° Semestre'), ('8', '8° Semestre'), ('9', '9° Semestre'), ('10', '10° Semestre'), ('11', '11° Semestre'), ('12', '12° Semestre')], max_length=2)),
                ('graduacao_turma', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ica.graduacao')),
            ],
        ),
        migrations.CreateModel(
            name='Estatistica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aluno_falta', models.CharField(max_length=5)),
                ('nota_pb1', models.CharField(blank=True, max_length=5, null=True)),
                ('nota_pb2', models.CharField(blank=True, max_length=5, null=True)),
                ('nota_pf', models.CharField(blank=True, default='-', max_length=5, null=True)),
                ('nota_atv1', models.CharField(blank=True, max_length=5, null=True)),
                ('nota_atv2', models.CharField(blank=True, max_length=5, null=True)),
                ('nota_atv3', models.CharField(blank=True, max_length=5, null=True)),
                ('nota_atv4', models.CharField(blank=True, max_length=5, null=True)),
                ('media_bm1', models.CharField(blank=True, max_length=5, null=True)),
                ('media_bm2', models.CharField(blank=True, max_length=5, null=True)),
                ('media_sm', models.CharField(blank=True, max_length=5, null=True)),
                ('media_fn', models.CharField(blank=True, default='-', max_length=5, null=True)),
                ('situação_sm', models.CharField(blank=True, max_length=20, null=True)),
                ('situação_fn', models.CharField(blank=True, default='-', max_length=20, null=True)),
                ('aluno_disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ica.disciplina')),
                ('aluno_matricula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='disciplina',
            name='graduacao_disciplina',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ica.graduacao'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='disciplina_professor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ica.disciplina'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
    ]
